$(document).ready(function () {
    Swal.fire({
        title: "ATENÇÃO",
        text: " FALSIDADE IDEOLÓGICA (CRIME PREVISTO NO ARTIGO 299 DO CÓDIGO PENAL) OMITIR, EM DOCUMENTO PÚBLICO OU PARTICULAR, DECLARAÇÃO QUE DELE DEVIA CONSTAR, OU NELE INSERIR OU FAZER INSERIR DECLARAÇÃO FALSA OU DIVERSA DA QUE DEVIA SER ESCRITA, COM O FIM DE PREJUDICAR DIREITO, CRIAR OBRIGAÇÃO OU ALTERAR A VERDADE SOBRE FATO JURIDICAMENTE RELEVANTE.",
        icon: "warning",
        width: 800,
        padding:50
    });
});
